{{- $dbPassword := .Values.global.database.password | required "global.database.password is required." -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.seatableFaasSchedulerDb.nameOverride }}: {{ .Values.global.database.password }}
  {{ if .Values.seatableFaasScheduler.config.serviceToken }}
  {{ .Values.seatableFaasScheduler.nameOverride }}-token: {{ .Values.seatableFaasScheduler.config.serviceToken }}
  {{ end }}