---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.seatableFaasScheduler.nameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seatable-faas.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "seatable-faas.selectorLabels" . | nindent 4 }}
    component: scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.seatableFaasSchedulerDb.nameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seatable-faas.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "seatable-faas.selectorLabels" . | nindent 4 }}
    component: database
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.seatablePythonRunner.nameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seatable-faas.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "seatable-faas.selectorLabels" . | nindent 4 }}
    component: runner
