---
pipeline:
  lint:
    image: alpine/helm:3.10.2
    commands:
      - apk add make
      - make lint

  deploy:
    image: quay.io/helmpack/chart-releaser:v1.5.0
    secrets:
      - GITHUB_TOKEN
    commands:
      - apk add make
      - make cr-release

when:
  branch:
    include:
      - master
    exclude:
      - renovate/*
  event:
    - push
  path:
    - "seatable-faas-stack/*"
